# Site settings
title: 博客呀博客
email: waynecraig2008@gmail.com
description: "哈哈，github page!"
baseurl: ""
url: "http://waynecraig.github.io"
twitter_username: waynecraig
github_username:  waynecraig

# Build settings
markdown: kramdown
permalink: pretty
